Increase database wait time

diff --git a/roles/node/init/templates/db.sh.j2 b/roles/node/init/templates/db.sh.j2
--- a/roles/node/init/templates/db.sh.j2
+++ b/roles/node/init/templates/db.sh.j2
@@ -12,11 +12,11 @@ ENABLE_CONSOLE={{ enable_console }}
 
 if [ "$NET_TYPE" == "internal" ]; then
     if [ ! -f "/tmp/install/waiting.db" ]; then
-        for ((i=1;i<=10;i++))
+        for ((i=1;i<=6;i++))
         do
-            num=$(curl -s --connect-timeout 5 $DB_HOST:$DB_PORT > /dev/null  && echo 1 || echo 0)
+            num=$(curl -s --connect-timeout 30 $DB_HOST:$DB_PORT > /dev/null  && echo 1 || echo 0)
             [ "$num" -ne 0 ] && echo "db is ok" && touch /tmp/install/waiting.db && break
-            sleep 10
+            sleep 5
         done
     fi
     DOCKER_CMD="docker exec rbd-db mysql -e"
@@ -71,9 +71,9 @@ EOF
 
 prepare(){
     local fail_num=0
-    for ((i=1;i<=10;i++))
+    for ((i=1;i<=6;i++))
     do
-        db_num=$(curl -s --connect-timeout 10 $DB_HOST:$DB_PORT > /dev/null  && echo 1 || echo 0)
+        db_num=$(curl -s --connect-timeout 30 $DB_HOST:$DB_PORT > /dev/null  && echo 1 || echo 0)
         if [ "$db_num" == 1 ]; then
             if [ "$ENABLE_CONSOLE" == "true" ]; then
                 $DOCKER_CMD "grant all on *.* to '{{ dbcs_user }}'@'%' identified by '{{ dbcs_pass }}' with grant option; flush privileges";
@@ -101,7 +101,7 @@ prepare(){
             sleep 10
         fi
     done
-    [ "$fail_num" == 10 ] && echo "prepare failed" && exit 1 || echo "prepare ok" && exit 0
+    [ "$fail_num" == 6 ] && echo "prepare failed" && exit 1 || echo "prepare ok" && exit 0
 }
 
 migrate_ui(){
