fix init r6d exit 0

diff --git a/roles/node/init/templates/initr6d.sh.j2 b/roles/node/init/templates/initr6d.sh.j2
--- a/roles/node/init/templates/initr6d.sh.j2
+++ b/roles/node/init/templates/initr6d.sh.j2
@@ -104,7 +104,7 @@ prepare(){
             sleep 10
         fi
     done
-    [ "$fail_num" == 10 ] && echo "prepare failed" && exit 1 || echo "prepare ok" && exit 0
+    [ "$fail_num" == 10 ] && echo "prepare failed" && exit 1 || echo "prepare ok" 
 }
 
 migrate_ui(){
@@ -125,7 +125,7 @@ migrate_ui(){
             sleep 10
         fi
     done
-    [ "$fail_num" ==10 ] && echo "migrate ui failed" && exit 1 || echo "migrate ui ok" && exit 0
+    [ "$fail_num" ==10 ] && echo "migrate ui failed" && exit 1 || echo "migrate ui ok" 
 }
 
 init_config(){
@@ -151,7 +151,7 @@ init_config(){
         ((fail_num+=1))
         sleep 5
     done
-    [ "$fail_num" == 10 ] && echo "init config failed" && exit 1 || echo "init config ok" && exit 0
+    [ "$fail_num" == 10 ] && echo "init config failed" && exit 1 || echo "init config ok" 
 }
 
 case $1 in
